---
title: "Ebola Analysis"
author: "Iyenoma Goodnews Osabuohien"
date: "2026-04-09"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages ----
if(!require(pacman)) install.packages("pacman")
pacman::p_load(
  tidyverse,
  janitor,
  inspectdf,
  flextable,
  here # new package we will use soon
)

ebola_sierra_leone <-read_csv(here("data/ebola_dat_raw-424c2e1f-88b5-4148-a370-b8ca5fad7088.csv")) # DATA PENDING! WE WILL UPDATE THIS BELOW.
```

# Case by district

this table shows counts of case by district

```{r echo=FALSE}

district_tab <- tabyl(ebola_sierra_leone, district)
flextable::flextable(district_tab)
```

# Visualize categorical variables ----

```{r echo=FALSE}
categ_vars_plot<- show_plot(inspect_cat(ebola_sierra_leone))
categ_vars_plot
```



# Visualize numeric variables ---

```{r echo=FALSE}
num_vars_plot <- show_plot(inspect_num(ebola_sierra_leone))
num_vars_plot
```


```{r}


# Load data ----  









```



#INTRODUCTION THE SELECT

```{r}
yoo <- 
  ebola_sierra_leone %>% select(age,
                                sex
                                )
```

